# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grounded_sam2_gPRC.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grounded_sam2_gPRC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grounded_sam2_gPRC.proto\x12\x04sam2\"-\n\nArrayInput\x12\x0f\n\x07img_arr\x18\x01 \x03(\x02\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"2\n\x0b\x41rrayOutput\x12#\n\nembeddings\x18\x01 \x03(\x0b\x32\x0f.sam2.Embedding\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32L\n\x0bSAM2Service\x12=\n\x14GetBatchedEmbeddings\x12\x10.sam2.ArrayInput\x1a\x11.sam2.ArrayOutput\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grounded_sam2_gPRC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARRAYINPUT']._serialized_start=34
  _globals['_ARRAYINPUT']._serialized_end=79
  _globals['_ARRAYOUTPUT']._serialized_start=81
  _globals['_ARRAYOUTPUT']._serialized_end=131
  _globals['_EMBEDDING']._serialized_start=133
  _globals['_EMBEDDING']._serialized_end=160
  _globals['_SAM2SERVICE']._serialized_start=162
  _globals['_SAM2SERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
